export enum ERolePermission {
    CREATE_USER = 'CREATE_USER',
    READ_USER = 'READ_USER',
    READ_ALL_USER = 'READ_ALL_USER',
    UPDATE_USER = 'UPDATE_USER',
    UPDATE_AVAILABLE_USER = 'UPDATE_AVAILABLE_USER',
    DELETE_USER = 'DELETE_USER',
    CREATE_ROLE = 'CREATE_ROLE',
    READ_ROLE = 'READ_ROLE',
    READ_ALL_ROLE = 'READ_ALL_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',
    UPDATE_AVAILABLE_ROLE = 'UPDATE_AVAILABLE_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',
}
